### PR TITLE
Always point to latest Cucumber & JUnit

### PR DESCRIPTION
**Pull request by searls**
(This is just a drive-by PR made via the web as I was reading this file; mea culpa)

In the skeleton projects I maintain, I hate having to manually bump versions to my libs, 
so this would let you prevent that by always running the latest version for new users

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Hmm - I think a lot of n00bs will struggle to figure out what to fill in for RELEASE ;-)

**Comment by searls** [comment]
IIRC, `RELEASE` is a special keyword for which Maven just automatically installs the latest version of the dependency

**Comment by aslakhellesoy** [comment]
Oh I didn't know that. However - there is still the `build.xml` to update, so we still need to keep the manual update process.

**Comment by wilsoncampusano** [comment]
Wow!!! that's a cool feature i didn't know!

**Pull request closed without merging**
