### PR TITLE
Add Gradle build - attempt #2

### PR DESCRIPTION
**Pull request by danielsiwiec**
Adding build.gradle

In comparison to the other, similar pull request, this one is a bit lighter and contains the critical

```
systemProperties = System.properties
```

part, which is necessary for the command line **cucumber.options="..."**. It took my quite a couple hours to figure this one out and would like to share it for others.

### CODE REVIEW

**Comment by danielsiwiec** [comment]
@aslakhellesoy Hey, what are your thoughts on this?

**Comment by WanderingKazuma** [comment]
Would very much appreciate if Gradle example was added. Also, if support for adding gradle tasks to execute by .feature instead of all at once would be nice for the larger projects that have multiple sections that need to be tested separately.

**Comment by aslakhellesoy** [comment]
Sorry for leaving this for so long.

Before merging this I'd like to see Cucumber's output in the console. All I see is this:

```
$ gradle test
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava
:processTestResources UP-TO-DATE
:testClasses
:test
```

How is the user supposed to see the step definition snippets printed by cucumber?

**Comment by tsundberg** [comment]
One way of seeing the step definition snippets is to lure Gradle into printing std out and std err to the console. It can be done by extending the test task like this: 

```
test {
    testLogging {
        showStandardStreams = true
    }
}
```
Adding `systemProperties System.getProperties()` to the test task will forward any command line options to the JVM running the tests.

```
test {
    testLogging {
        showStandardStreams = true
    }

    systemProperties System.getProperties()
}
```
With these extensions to the test task, I am able to get Gradle to behave resonably with Cucumber-JVM.

I would, however, consider adding [Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html) as well to get a completely self sustaining example.

**Comment by danielsiwiec** [comment]
@aslakhellesoy @tsundberg I addressed your concerns. Please take a look

**Comment by tsundberg** [comment]
Replaced by https://github.com/cucumber/cucumber-java-skeleton/pull/16

**Pull request closed without merging**
