### PR TITLE
Update to Cucumber 4.5.4

### PR DESCRIPTION
**Pull request by Riggs333**

### CODE REVIEW

**Comment by mpkorstanje** [comment]
Cheers again. However 4.5 deprecates quite a few methods. They're not recognized by IDEA or Eclipse yet so I'd hold off on this one for a little bit.

**Comment by Riggs333** [comment]
I agree this should be postponed until IntelliJ supports the new Cucumber annotations, see https://youtrack.jetbrains.com/issue/IDEA-217391

**Comment by beardedqa** [comment]
@Riggs333 as we have 4.5.4 already, I updated the version. Waiting for cucumber plugin :)

**Comment by mpkorstanje** [comment]
Cheers all. Cucumber v5 is getting close so I'm putting in 4.7.2 now.

**Pull request closed without merging**
