### PR TITLE
Update to Gradle 5.5

### PR DESCRIPTION
**Pull request by Riggs333**
Replace deprecated dependency configuration `testCompile` with
`testImplementation`, see Gradle documentation
https://docs.gradle.org/current/userguide/java_plugin.html#tab:configurations

### CODE REVIEW

**Comment by mpkorstanje** [comment]
Cheers. How did you generate/create the changes to  `gradlew`/ `gradlew.bat`?

**Comment by Riggs333** [comment]
On my local Ubuntu environment I ran
```shell
./gradlew wrapper --gradle-version=5.5 --distribution-type all
```

**Comment by aslakhellesoy** [comment]
Hi @Riggs333,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by mpkorstanje** [comment]
Cheers. That made it much easier to verify the correctness.

**Pull request merged**
